# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_introductions_brief_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='introductions',
            name='file',
            field=models.FileField(default=1, upload_to='./static/img'),
            preserve_default=False,
        ),
    ]
