# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_introductions_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introductions',
            name='file',
            field=models.ImageField(upload_to='./static/img/'),
        ),
    ]
