# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introductions',
            name='file',
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='static/img/', verbose_name='File'),
        ),
    ]
