# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171221_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='title',
            new_name='title_gallery',
        ),
    ]
