# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20171222_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='introductions',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='introductions',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=258, verbose_name='举办地点'),
            preserve_default=False,
        ),
    ]
