# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20171225_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='translations',
        ),
        migrations.RemoveField(
            model_name='articletranslation',
            name='article_instance',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleTranslation',
        ),
    ]
