# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_introductions_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='introductions',
            name='zh_content',
            field=models.TextField(default=1, verbose_name='内容'),
            preserve_default=False,
        ),
    ]
