# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_introductions_zh_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='capture',
            field=models.CharField(default=1, max_length=256, verbose_name='Capture'),
            preserve_default=False,
        ),
    ]
